// Tënkui 2026 — Master data
// Source: Catálogo Maestro de Programación Tënkui 2026

const VENUES = {
  'casa-titeres-monini': {
    id: 'casa-titeres-monini',
    name: 'Casa de los títeres MONINI',
    short: 'MONINI',
    address: 'Morelos #1065, Zona Centro',
    barrio: 'Centro Histórico',
    tags: ['Teatro Familiar', 'Centro Histórico'],
    description: 'Un espacio mágico en el corazón de San Luis Potosí dedicado al arte de los títeres y la imaginación.',
    features: ['Espacio climatizado', 'Acceso para carriolas', 'Área de café y cuentos'],
    accent: '#C7553F',
    illo: 'titeres',
  },
  'semillas-suzuki': {
    id: 'semillas-suzuki',
    name: 'Semillas Suzuki',
    short: 'Suzuki',
    address: 'Alfredo M. Terrazas #305, Col. Tequisquiapan',
    barrio: 'Tequisquiapan',
    tags: ['Educación Musical', 'Familiar'],
    description: 'Centro de Educación Musical donde la melodía y la palabra se encuentran para sembrar oído y memoria.',
    features: ['Sala de música', 'Apto para bebés', 'Apoyos pedagógicos'],
    accent: '#8FD2C0',
    illo: 'musica',
  },
  'kuestudio': {
    id: 'kuestudio',
    name: "Ku'estudio",
    short: "Ku'estudio",
    address: 'Av. Constitución #1105-B, Barrio de San Sebastián',
    barrio: 'San Sebastián',
    tags: ['Estudio', 'Percusión'],
    description: 'Un estudio íntimo para la percusión y los ritmos colectivos en uno de los barrios más entrañables de la ciudad.',
    features: ['Piso flotante', 'Instrumentos en sitio', 'Patio interior'],
    accent: '#F2B544',
    illo: 'tambor',
  },
  'arte-indigo': {
    id: 'arte-indigo',
    name: 'Arte Índigo',
    short: 'Índigo',
    address: 'Martínez de Castro #106, Col. Centro',
    barrio: 'Centro',
    tags: ['Artes Plásticas', 'Taller'],
    description: 'Casa-taller dedicada al grabado, las artes plásticas y los oficios de la mano.',
    features: ['Prensas activas', 'Materiales incluidos', 'Áreas al aire libre'],
    accent: '#6B8AD6',
    illo: 'grabado',
  },
  'letrasconmas': {
    id: 'letrasconmas',
    name: 'Letrasconmás',
    short: 'Letrasconmás',
    address: 'Prol. Santos Degollado #1220 esq. Ejército Nacional',
    barrio: 'Ejército Nacional',
    tags: ['Librería', 'Biblioteca infantil'],
    description: 'Librería y biblioteca infantil donde los libros viven y se prestan a la lectura compartida.',
    features: ['Acervo infantil', 'Sala de lectura', 'Cojines y alfombras'],
    accent: '#F08D6E',
    illo: 'libros',
  },
  'ipba-raul-gamboa': {
    id: 'ipba-raul-gamboa',
    name: 'Centro de Difusión Cultural Raúl Gamboa I.P.B.A.',
    short: 'Raúl Gamboa',
    address: 'Av. Universidad esq. C. Negrete S/N, Centro',
    barrio: 'Centro',
    tags: ['Centro Cultural', 'I.P.B.A.'],
    description: 'Foro cultural del Instituto Potosino de Bellas Artes, hogar de las artes escénicas universitarias.',
    features: ['Foro escénico', 'Camerinos', 'Cupo amplio'],
    accent: '#A66BB0',
    illo: 'foro',
  },
  'muni-uaslp': {
    id: 'muni-uaslp',
    name: 'MUNI · Museo Universitario UASLP',
    short: 'MUNI',
    address: 'Av. Sierra Leona 550, Lomas 2da sección',
    barrio: 'Lomas',
    tags: ['Museo', 'UASLP'],
    description: 'Museo universitario donde la mirada infantil se vuelve materia de exposición y juego.',
    features: ['Salas climatizadas', 'Estacionamiento', 'Accesible'],
    accent: '#5A8A6E',
    illo: 'museo',
  },
};

const EVENTS = [
  {
    id: 'pipi-la-noche',
    title: 'Pipí la noche',
    company: 'Casa de los títeres MONINI',
    discipline: 'Teatro de Títeres',
    disciplineKey: 'escenicas',
    tags: ['#TeatroDeTíteres', '#ArtesEscénicas', '#SanLuisPotosí'],
    age: '2+ años',
    ageKey: 'todos',
    date: '29 de abril',
    dateISO: '2026-04-29',
    day: 'Mié',
    time: '5:00 p.m.',
    duration: '60 min',
    venue: 'casa-titeres-monini',
    cost: 'cooperacion',
    costLabel: 'Cooperación · desde $80',
    costTiers: [
      { window: 'A partir del 13 de abril', adult: 120, kid: 80 },
      { window: 'A partir del 24 de abril', adult: 140, kid: 100 },
    ],
    synopsis: 'Diego, un niño de 7 años avergonzado por usar pañal durante las noches, se aventura a descubrir el motivo de hacerse pipí en la cama para poder luchar contra ello. En un mundo de aventuras imaginarias y lleno de experiencias extraordinarias, Diego logra superar su problema.',
    crew: [
      { role: 'Autor y dirección', name: 'Sandra Delgado', icon: 'pen' },
      { role: 'Música original', name: 'Nicolas Alfonso', icon: 'music' },
      { role: 'Manipulación', name: 'Sandra Delgado, Sheila Sierra', icon: 'hand' },
    ],
    accent: '#C7553F',
    bg: 'curtain-warm',
    featured: true,
    kind: 'obra',
  },
  {
    id: 'duanop',
    title: 'DUANOP',
    subtitle: 'Teatro para bebés',
    company: '¡Caracoles! Danza Teatro',
    discipline: 'Danza Teatro',
    disciplineKey: 'escenicas',
    tags: ['#TeatroParaBebés', '#PrimeraInfancia', '#DanzaTeatro'],
    age: '6 meses a 4 años',
    ageKey: 'primera-infancia',
    date: '30 de abril',
    dateISO: '2026-04-30',
    day: 'Jue',
    time: '4:30 p.m. y 5:30 p.m.',
    duration: '40 min',
    venue: 'ipba-raul-gamboa',
    cost: 'libre',
    costLabel: 'Entrada libre · cupo limitado',
    costNote: 'Espectáculo para la primera infancia. No requiere registro previo, anticipa tu llegada.',
    synopsis: '"DUANOP" es una experiencia escénica dirigida a primeras infancias donde solo basta encontrarse para empezar a jugar; un espacio donde todos los lugares se vuelven posibles: la cochera, la sala y el jardín se vuelven mundos extraordinarios.',
    crew: [
      { role: 'Idea original', name: 'Mayela Guadarrama Briones', icon: 'spark' },
      { role: 'Equipo creativo', name: 'Mayela Guadarrama, Jacobo Núñez, Miriam Castillo', icon: 'group' },
    ],
    accent: '#8FD2C0',
    bg: 'soft-blue',
    featured: true,
    kind: 'obra',
  },
  {
    id: 'cuentacuentos-familias',
    title: 'Cuentacuentos para familias que no saben qué leer',
    short: 'Cuentacuentos',
    company: 'Gustoño y la Lupita',
    discipline: 'Narración Oral',
    disciplineKey: 'literatura',
    tags: ['#NarraciónOral', '#LiteraturaInfantil', '#MúsicaTradicional'],
    age: '6 a 12 años',
    ageKey: 'mayores',
    date: '1 de mayo',
    dateISO: '2026-05-01',
    day: 'Vie',
    time: '12:00 p.m.',
    duration: '50 min',
    venue: 'semillas-suzuki',
    cost: 'cooperacion',
    costLabel: 'Cooperación · desde $80',
    costTiers: [
      { window: 'A partir del 13 de abril', adult: 120, kid: 80 },
      { window: 'A partir del 24 de abril', adult: 140, kid: 100 },
    ],
    synopsis: 'Con esta presentación se refuerza el valor de la lectura y se presentan diversos cuentos infantiles, dirigido a familias que no saben por dónde empezar cuando llega el momento de iniciar su acervo de literatura infantil. La narración oral irá acompañada de música con instrumentos tradicionales mexicanos.',
    crew: [
      { role: 'Artistas', name: 'Gustavo Antonio Salazar Pérez, Irma Zamora', icon: 'group' },
    ],
    accent: '#F08D6E',
    bg: 'cream',
    featured: false,
    kind: 'taller',
  },
  {
    id: 'la-raiz-del-nido',
    title: 'La raíz del nido',
    company: 'Garúa',
    discipline: 'Teatro Sensorial',
    disciplineKey: 'escenicas',
    tags: ['#TeatroSensorial', '#PrimeraInfancia', '#MúsicaEnVivo'],
    age: 'Primera infancia',
    ageKey: 'primera-infancia',
    date: '2 de mayo',
    dateISO: '2026-05-02',
    day: 'Sáb',
    time: '10:00 a.m.',
    duration: '45 min',
    venue: 'muni-uaslp',
    cost: 'cooperacion',
    costLabel: 'Cooperación · desde $80',
    costTiers: [
      { window: 'A partir del 13 de abril', adult: 120, kid: 80 },
      { window: 'A partir del 24 de abril', adult: 140, kid: 100 },
    ],
    synopsis: '"La raíz del nido" es una puesta en escena dirigida a primeras infancias que, mediante la poesía, música en vivo y distintos elementos visuales, nos invita a recorrer un viaje por los elementos que nos acompañan en el crecer: agua, tierra, fuego y aire. Una experiencia musical que nos convoca a ser espectadores y partícipes de un ambiente cuidado y sensible.',
    crew: [
      { role: 'Dirección', name: 'Adriana Aguilar Hervert', icon: 'pen' },
      { role: 'Músicos', name: 'Irma Zamora, Daniel Uresti, Teodoro Munguía, Adriana Aguilar', icon: 'music' },
    ],
    accent: '#5A8A6E',
    bg: 'forest',
    featured: true,
    kind: 'obra',
  },
  {
    id: 'entre-libros-y-arrullos',
    title: 'Entre libros y arrullos',
    company: 'Maru Urbina',
    discipline: 'Taller Literario',
    disciplineKey: 'literatura',
    tags: ['#TallerLiterario', '#LecturaTemprana', '#PrimeraInfancia'],
    age: '2 a 5 años',
    ageKey: 'primera-infancia',
    date: '2 de mayo',
    dateISO: '2026-05-02',
    day: 'Sáb',
    time: '1:00 p.m.',
    duration: '60 min',
    venue: 'letrasconmas',
    cost: 'cooperacion-anticipada',
    costLabel: 'Cooperación anticipada · 1 infancia + 1 adulto',
    costTiers: [
      { window: 'A partir del 13 de abril', adult: 120, kid: 80 },
      { window: 'A partir del 24 de abril', adult: 140, kid: 100 },
    ],
    costNote: 'Entrada con cooperación anticipada (infancia + un adulto acompañante).',
    synopsis: 'Un taller en el que compartiremos lecturas con las niñas y los niños más pequeños. A partir de los libros, del juego del lenguaje y del movimiento vamos a crear experiencias literarias desde la primera infancia.',
    crew: [
      { role: 'Responsable', name: 'Ma. Eugenia Urbina Espejel', icon: 'book' },
    ],
    accent: '#F08D6E',
    bg: 'soft-peach',
    featured: false,
    kind: 'taller',
  },
  {
    id: 'transferencias-graficas',
    title: 'Transferencias Gráficas',
    company: 'Arte Índigo · Alejandra González Fraga',
    discipline: 'Grabado',
    disciplineKey: 'plasticas',
    tags: ['#Grabado', '#ArtesPlásticas', '#TallerInfantil'],
    age: '8 a 13 años',
    ageKey: 'mayores',
    date: '2 de mayo',
    dateISO: '2026-05-02',
    day: 'Sáb',
    time: '4:00 p.m.',
    duration: '90 min',
    venue: 'arte-indigo',
    cost: 'cooperacion',
    costLabel: 'Cooperación · desde $80',
    costTiers: [
      { window: 'A partir del 13 de abril', adult: 120, kid: 80 },
      { window: 'A partir del 24 de abril', adult: 140, kid: 100 },
    ],
    synopsis: 'En este taller, las y los participantes descubrirán el fascinante mundo del grabado a través de técnicas como relieve y hueco, explorando cómo una imagen puede reproducirse a partir de una matriz creada por ellos mismos. Al finalizar, cada participante contará con sus propias estampas y matrices, entendiendo el grabado no solo como una técnica, sino como una forma de expresión artística.',
    crew: [
      { role: 'Artista visual', name: 'Alejandra González Fraga', icon: 'pen' },
    ],
    accent: '#6B8AD6',
    bg: 'soft-indigo',
    featured: false,
    kind: 'taller',
  },
  {
    id: 'fiesta-de-tambores',
    title: 'Fiesta de tambores',
    company: 'Ensamble Semillas Suzuki',
    discipline: 'Taller Musical',
    disciplineKey: 'musica',
    tags: ['#TallerMusical', '#Percusión', '#MúsicaAfroLatina'],
    age: '2+ años',
    ageKey: 'todos',
    date: '3 de mayo',
    dateISO: '2026-05-03',
    day: 'Dom',
    time: '10:30 a.m.',
    duration: '60 min',
    venue: 'kuestudio',
    cost: 'libre-registro',
    costLabel: 'Entrada libre · registro previo · 1 infancia + 1 adulto',
    costNote: 'Entrada libre con registro previo (infancia + un adulto acompañante). Envía un mensaje vía WhatsApp para registrar tu lugar.',
    synopsis: 'La Fiesta de tambores es un taller lúdico para explorar con nuestra voz, la percusión y el movimiento distintas músicas afro-latinas. Será un momento de mucho juego y goce compartido. No es necesario tener conocimientos musicales: ¡aquí vamos a divertirnos y explorar en familia!',
    crew: [
      { role: 'Ensamble', name: 'Mónica Almendarez, Dionisio Alzaga, Adriana Aguilar', icon: 'group' },
    ],
    accent: '#F2B544',
    bg: 'mustard',
    featured: true,
    kind: 'taller',
  },
  {
    id: 'los-males-invisibles',
    title: 'Los males invisibles',
    company: '¡Caracoles! Danza Teatro',
    discipline: 'Drama Contemporáneo',
    disciplineKey: 'escenicas',
    tags: ['#DramaContemporáneo', '#ArtesEscénicas', '#Valores'],
    age: '4+ años',
    ageKey: 'todos',
    date: '3 de mayo',
    dateISO: '2026-05-03',
    day: 'Dom',
    time: '4:00 p.m.',
    duration: '55 min',
    venue: 'arte-indigo',
    cost: 'cooperacion',
    costLabel: 'Cooperación · desde $80',
    costTiers: [
      { window: 'A partir del 13 de abril', adult: 120, kid: 80 },
      { window: 'A partir del 24 de abril', adult: 140, kid: 100 },
    ],
    synopsis: 'Un drama contemporáneo interactivo para las infancias, donde dos cuentacuentos nómadas llevan por un viaje imaginario a través de sus asombrosas historias, reconociendo los males que habitan en el mundo y que son invisibles a nuestra mirada pero quiebran los valores de las infancias que construyen mundo día con día. Descubrir que lo que uno siembra en su vida lo habrá de cosechar será la barca para navegar por la imaginación y la aventura.',
    crew: [
      { role: 'Dirección escénica', name: 'Jacobo Núñez', icon: 'pen' },
      { role: 'Dramaturgia', name: 'Jacobo Núñez, Mayela Guadarrama', icon: 'book' },
      { role: 'Elenco', name: 'Luisa Olivares, Eli Durán', icon: 'group' },
    ],
    accent: '#A66BB0',
    bg: 'plum',
    featured: false,
    kind: 'obra',
  },
  {
    id: 'fanzinoteka',
    title: 'Galería: la fanzinoteka escolar',
    short: 'Fanzinoteka escolar',
    company: 'Telar de escritura',
    discipline: 'Galería itinerante',
    disciplineKey: 'plasticas',
    tags: ['#Fanzine', '#Exposición', '#Comunidad'],
    age: 'Todo público',
    ageKey: 'todos',
    date: '1–3 de mayo',
    dateISO: '2026-05-01',
    day: 'Itin.',
    time: 'Antesala de funciones',
    duration: 'Itinerante',
    venue: 'semillas-suzuki',
    venuesItinerant: [
      { date: '1 de mayo · 11:30 a.m.', venue: 'semillas-suzuki' },
      { date: '2 de mayo · 9:30 a.m.', venue: 'muni-uaslp' },
      { date: '3 de mayo · 3:30 p.m.', venue: 'arte-indigo' },
    ],
    cost: 'libre',
    costLabel: 'Entrada libre · sin registro',
    costNote: 'Galería itinerante. Entrada libre sin registro previo, se encontrará en la antesala de las funciones.',
    synopsis: 'El fanzine es una herramienta artística para que niñas y niños plasmen con creatividad sentimientos e ideas, en un formato fácilmente reproducible y compartible. Tiene un gran poder comunitario.',
    crew: [
      { role: 'Artista', name: 'Gustavo Antonio Salazar Pérez', icon: 'pen' },
    ],
    accent: '#E8C66B',
    bg: 'paper',
    featured: false,
    kind: 'galeria',
  },
];

const DISCIPLINES = [
  { key: 'todas', label: 'Todas' },
  { key: 'escenicas', label: 'Artes Escénicas' },
  { key: 'literatura', label: 'Literatura' },
  { key: 'musica', label: 'Música' },
  { key: 'plasticas', label: 'Artes Plásticas' },
];

const DAYS = [
  { key: 'todos', label: 'Todos los días', date: '29 abr — 3 may' },
  { key: '2026-04-29', label: 'Miércoles', date: '29 abr' },
  { key: '2026-04-30', label: 'Jueves', date: '30 abr' },
  { key: '2026-05-01', label: 'Viernes', date: '1 may' },
  { key: '2026-05-02', label: 'Sábado', date: '2 may' },
  { key: '2026-05-03', label: 'Domingo', date: '3 may' },
];

const AGES = [
  { key: 'todas', label: 'Todas las edades' },
  { key: 'primera-infancia', label: 'Primera infancia' },
  { key: 'todos', label: 'En familia' },
  { key: 'mayores', label: '6+ años' },
];

const COSTS = [
  { key: 'todos', label: 'Cualquier acceso' },
  { key: 'libre', label: 'Entrada libre' },
  { key: 'cooperacion', label: 'Cooperación' },
];

// Photo URLs (official posters from Tënkui 2026)
const PHOTOS = {
  'pipi-la-noche': 'posters/02-pipi-la-noche.jpg',
  'duanop': 'posters/03-duanop.jpg',
  'cuentacuentos-familias': 'posters/04-cuentacuentos.jpg',
  'la-raiz-del-nido': 'posters/05-la-raiz-del-nido.jpg',
  'entre-libros-y-arrullos': 'posters/06-entre-libros-y-arrullos.jpg',
  'fiesta-de-tambores': 'posters/07-fiesta-de-tambores.jpg',
  'transferencias-graficas': 'posters/08-transferencias-graficas.jpg',
  'los-males-invisibles': 'posters/09-los-males-invisibles.jpg',
  'fanzinoteka': 'posters/10-fanzinoteka.jpg',
};
const VENUE_PHOTOS = {
  'casa-titeres-monini': 'posters/02-pipi-la-noche.jpg',
  'semillas-suzuki': 'posters/04-cuentacuentos.jpg',
  'kuestudio': 'posters/07-fiesta-de-tambores.jpg',
  'arte-indigo': 'posters/08-transferencias-graficas.jpg',
  'letrasconmas': 'posters/06-entre-libros-y-arrullos.jpg',
  'ipba-raul-gamboa': 'posters/03-duanop.jpg',
  'muni-uaslp': 'posters/05-la-raiz-del-nido.jpg',
};

const WHATSAPP = '524447027037';
const WHATSAPP_DISPLAY = '444 702 7037';

Object.assign(window, { VENUES, EVENTS, DISCIPLINES, DAYS, AGES, COSTS, WHATSAPP, WHATSAPP_DISPLAY, PHOTOS, VENUE_PHOTOS });
